// Please use the following editor setup for this file:
// Tab size=2; Tabs as spaces; Clean up trailing whitepsace
//
// In vim add: au FileType proto setl sw=2 ts=2 expandtab list
//
// In vscode install vscode-proto3 extension and add this to your settings.json:
//    "[proto3]": {
//        "editor.tabSize": 2,
//        "editor.insertSpaces": true,
//        "editor.rulers": [80],
//        "editor.detectIndentation": true,
//        "files.trimTrailingWhitespace": true
//    }
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: hello/apiv1/hello.proto

package hello

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// These values are constants that can be used by the
// client and server applications
type HelloVersion_Version int32

const (
	// Must be set in the proto file; ignore.
	HelloVersion_VERSION_UNSPECIFIED HelloVersion_Version = 0
	// Version major value of this specification
	HelloVersion_MAJOR HelloVersion_Version = 0
	// Version minor value of this specification
	HelloVersion_MINOR HelloVersion_Version = 0
	// Version patch value of this specification
	HelloVersion_PATCH HelloVersion_Version = 1
)

// Enum value maps for HelloVersion_Version.
var (
	HelloVersion_Version_name = map[int32]string{
		0: "VERSION_UNSPECIFIED",
		// Duplicate value: 0: "MAJOR",
		// Duplicate value: 0: "MINOR",
		1: "PATCH",
	}
	HelloVersion_Version_value = map[string]int32{
		"VERSION_UNSPECIFIED": 0,
		"MAJOR":               0,
		"MINOR":               0,
		"PATCH":               1,
	}
)

func (x HelloVersion_Version) Enum() *HelloVersion_Version {
	p := new(HelloVersion_Version)
	*p = x
	return p
}

func (x HelloVersion_Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HelloVersion_Version) Descriptor() protoreflect.EnumDescriptor {
	return file_hello_apiv1_hello_proto_enumTypes[0].Descriptor()
}

func (HelloVersion_Version) Type() protoreflect.EnumType {
	return &file_hello_apiv1_hello_proto_enumTypes[0]
}

func (x HelloVersion_Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HelloVersion_Version.Descriptor instead.
func (HelloVersion_Version) EnumDescriptor() ([]byte, []int) {
	return file_hello_apiv1_hello_proto_rawDescGZIP(), []int{4, 0}
}

// The request message containing the user's name.
type SayHelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name to say hello to
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_hello_apiv1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_apiv1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_hello_apiv1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type SayHelloResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message returned from server containing 'name'
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_hello_apiv1_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_apiv1_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_hello_apiv1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Empty request
type ServerVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerVersionRequest) Reset() {
	*x = ServerVersionRequest{}
	mi := &file_hello_apiv1_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerVersionRequest) ProtoMessage() {}

func (x *ServerVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_apiv1_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerVersionRequest.ProtoReflect.Descriptor instead.
func (*ServerVersionRequest) Descriptor() ([]byte, []int) {
	return file_hello_apiv1_hello_proto_rawDescGZIP(), []int{2}
}

// Defines the response to version
type ServerVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hello application version
	ServerVersion *HelloVersion `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerVersionResponse) Reset() {
	*x = ServerVersionResponse{}
	mi := &file_hello_apiv1_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerVersionResponse) ProtoMessage() {}

func (x *ServerVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_apiv1_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerVersionResponse.ProtoReflect.Descriptor instead.
func (*ServerVersionResponse) Descriptor() ([]byte, []int) {
	return file_hello_apiv1_hello_proto_rawDescGZIP(), []int{3}
}

func (x *ServerVersionResponse) GetServerVersion() *HelloVersion {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

// Hello version in Major.Minor.Patch format. The goal of this
// message is to provide clients a method to determine the server
// and client versions.
type HelloVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version major number
	Major int32 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	// Version minor number
	Minor int32 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	// Version patch number
	Patch int32 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	// String representation of the version. Must be
	// in `major.minor.patch` format.
	Version       string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloVersion) Reset() {
	*x = HelloVersion{}
	mi := &file_hello_apiv1_hello_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloVersion) ProtoMessage() {}

func (x *HelloVersion) ProtoReflect() protoreflect.Message {
	mi := &file_hello_apiv1_hello_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloVersion.ProtoReflect.Descriptor instead.
func (*HelloVersion) Descriptor() ([]byte, []int) {
	return file_hello_apiv1_hello_proto_rawDescGZIP(), []int{4}
}

func (x *HelloVersion) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *HelloVersion) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *HelloVersion) GetPatch() int32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *HelloVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_hello_apiv1_hello_proto protoreflect.FileDescriptor

const file_hello_apiv1_hello_proto_rawDesc = "" +
	"\n" +
	"\x17hello/apiv1/hello.proto\x12\x0ehello.hello.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"*\n" +
	"\x0fSayHelloRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x16\n" +
	"\x14ServerVersionRequest\"\\\n" +
	"\x15ServerVersionResponse\x12C\n" +
	"\x0eserver_version\x18\x01 \x01(\v2\x1c.hello.hello.v1.HelloVersionR\rserverVersion\"\xb3\x01\n" +
	"\fHelloVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\x05R\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\x05R\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\x05R\x05patch\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"G\n" +
	"\aVersion\x12\x17\n" +
	"\x13VERSION_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05MAJOR\x10\x00\x12\t\n" +
	"\x05MINOR\x10\x00\x12\t\n" +
	"\x05PATCH\x10\x01\x1a\x02\x10\x012~\n" +
	"\fHelloGreeter\x12n\n" +
	"\bSayHello\x12\x1f.hello.hello.v1.SayHelloRequest\x1a .hello.hello.v1.SayHelloResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/greeter:sayHello2\x92\x01\n" +
	"\rHelloIdentity\x12\x80\x01\n" +
	"\rServerVersion\x12$.hello.hello.v1.ServerVersionRequest\x1a%.hello.hello.v1.ServerVersionResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/identity:serverVersionBn\n" +
	"\x12com.hello.hello.v1B\n" +
	"HelloProtoP\x01ZJgithub.com/grpc-framework/grpc-framework/v2/example/apis/hello/apiv1;hellob\x06proto3"

var (
	file_hello_apiv1_hello_proto_rawDescOnce sync.Once
	file_hello_apiv1_hello_proto_rawDescData []byte
)

func file_hello_apiv1_hello_proto_rawDescGZIP() []byte {
	file_hello_apiv1_hello_proto_rawDescOnce.Do(func() {
		file_hello_apiv1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hello_apiv1_hello_proto_rawDesc), len(file_hello_apiv1_hello_proto_rawDesc)))
	})
	return file_hello_apiv1_hello_proto_rawDescData
}

var file_hello_apiv1_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hello_apiv1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hello_apiv1_hello_proto_goTypes = []any{
	(HelloVersion_Version)(0),     // 0: hello.hello.v1.HelloVersion.Version
	(*SayHelloRequest)(nil),       // 1: hello.hello.v1.SayHelloRequest
	(*SayHelloResponse)(nil),      // 2: hello.hello.v1.SayHelloResponse
	(*ServerVersionRequest)(nil),  // 3: hello.hello.v1.ServerVersionRequest
	(*ServerVersionResponse)(nil), // 4: hello.hello.v1.ServerVersionResponse
	(*HelloVersion)(nil),          // 5: hello.hello.v1.HelloVersion
}
var file_hello_apiv1_hello_proto_depIdxs = []int32{
	5, // 0: hello.hello.v1.ServerVersionResponse.server_version:type_name -> hello.hello.v1.HelloVersion
	1, // 1: hello.hello.v1.HelloGreeter.SayHello:input_type -> hello.hello.v1.SayHelloRequest
	3, // 2: hello.hello.v1.HelloIdentity.ServerVersion:input_type -> hello.hello.v1.ServerVersionRequest
	2, // 3: hello.hello.v1.HelloGreeter.SayHello:output_type -> hello.hello.v1.SayHelloResponse
	4, // 4: hello.hello.v1.HelloIdentity.ServerVersion:output_type -> hello.hello.v1.ServerVersionResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hello_apiv1_hello_proto_init() }
func file_hello_apiv1_hello_proto_init() {
	if File_hello_apiv1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_apiv1_hello_proto_rawDesc), len(file_hello_apiv1_hello_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_hello_apiv1_hello_proto_goTypes,
		DependencyIndexes: file_hello_apiv1_hello_proto_depIdxs,
		EnumInfos:         file_hello_apiv1_hello_proto_enumTypes,
		MessageInfos:      file_hello_apiv1_hello_proto_msgTypes,
	}.Build()
	File_hello_apiv1_hello_proto = out.File
	file_hello_apiv1_hello_proto_goTypes = nil
	file_hello_apiv1_hello_proto_depIdxs = nil
}
