sudo: required
services:
  - docker
language: go
go:
  - 1.21.x
install:
  - GO111MODULE=off go get -u github.com/vbatts/git-validation
jobs:
  include:
    - stage: PR Verify & e2e tests
      script: 
        - make travis-verify
