/// Please use the following editor setup for this file:
// Tab size=2; Tabs as spaces; Clean up trailing whitepsace
//
// In vim add: au FileType proto setl sw=2 ts=2 expandtab list
//
// In vscode install vscode-proto3 extension and add this to your settings.json:
//    "[proto3]": {
//        "editor.tabSize": 2,
//        "editor.insertSpaces": true,
//        "editor.rulers": [80],
//        "editor.detectIndentation": true,
//        "files.trimTrailingWhitespace": true
//    }
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: apis/auth/apiv1/ownership.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Access types can be set by owner to have different levels of access to
// a resource.
//
// It is up to the resource to interpret what the types mean and are
// used for.
// (-- api-linter: core::0126::unspecified=disabled
//
//	aip.dev/not-precedent: Have READ as 0 on purpose as the default. --)
type Ownership_AccessType int32

const (
	// Read access only and cannot affect the resource.
	Ownership_READ Ownership_AccessType = 0
	// Write access and can affect the resource.
	// This type automatically provides Read access also.
	Ownership_WRITE Ownership_AccessType = 1
	// Administrator access.
	// This type automatically provides Read and Write access also.
	Ownership_ADMIN Ownership_AccessType = 2
)

// Enum value maps for Ownership_AccessType.
var (
	Ownership_AccessType_name = map[int32]string{
		0: "READ",
		1: "WRITE",
		2: "ADMIN",
	}
	Ownership_AccessType_value = map[string]int32{
		"READ":  0,
		"WRITE": 1,
		"ADMIN": 2,
	}
)

func (x Ownership_AccessType) Enum() *Ownership_AccessType {
	p := new(Ownership_AccessType)
	*p = x
	return p
}

func (x Ownership_AccessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ownership_AccessType) Descriptor() protoreflect.EnumDescriptor {
	return file_apis_auth_apiv1_ownership_proto_enumTypes[0].Descriptor()
}

func (Ownership_AccessType) Type() protoreflect.EnumType {
	return &file_apis_auth_apiv1_ownership_proto_enumTypes[0]
}

func (x Ownership_AccessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ownership_AccessType.Descriptor instead.
func (Ownership_AccessType) EnumDescriptor() ([]byte, []int) {
	return file_apis_auth_apiv1_ownership_proto_rawDescGZIP(), []int{0, 0}
}

// Ownership information for resource.
// Administrators are users who belong to the group `*`, meaning, every group.
type Ownership struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username of owner.
	//
	// The storage system uses the username taken from the security authorization
	// token and is saved on this field. Only users with system administration
	// can edit this value.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// Permissions to share resource which can be set by the owner.
	//
	// NOTE: To create an "admin" user which has access to any resource set the group value
	// in the token of the user to `*`.
	Acls          *Ownership_AccessControl `protobuf:"bytes,2,opt,name=acls,proto3" json:"acls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ownership) Reset() {
	*x = Ownership{}
	mi := &file_apis_auth_apiv1_ownership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ownership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ownership) ProtoMessage() {}

func (x *Ownership) ProtoReflect() protoreflect.Message {
	mi := &file_apis_auth_apiv1_ownership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ownership.ProtoReflect.Descriptor instead.
func (*Ownership) Descriptor() ([]byte, []int) {
	return file_apis_auth_apiv1_ownership_proto_rawDescGZIP(), []int{0}
}

func (x *Ownership) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Ownership) GetAcls() *Ownership_AccessControl {
	if x != nil {
		return x.Acls
	}
	return nil
}

// PublicAccessControl allows assigning public ownership
type Ownership_PublicAccessControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AccessType declares which level of public access is allowed
	Type          Ownership_AccessType `protobuf:"varint,1,opt,name=type,proto3,enum=apis.auth.v1.Ownership_AccessType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ownership_PublicAccessControl) Reset() {
	*x = Ownership_PublicAccessControl{}
	mi := &file_apis_auth_apiv1_ownership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ownership_PublicAccessControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ownership_PublicAccessControl) ProtoMessage() {}

func (x *Ownership_PublicAccessControl) ProtoReflect() protoreflect.Message {
	mi := &file_apis_auth_apiv1_ownership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ownership_PublicAccessControl.ProtoReflect.Descriptor instead.
func (*Ownership_PublicAccessControl) Descriptor() ([]byte, []int) {
	return file_apis_auth_apiv1_ownership_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Ownership_PublicAccessControl) GetType() Ownership_AccessType {
	if x != nil {
		return x.Type
	}
	return Ownership_READ
}

// AccessControl authorizes access to resources
type Ownership_AccessControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group access to resource which must match the group set in the
	// authorization token.
	// Can be set by the owner or the system administrator only.
	// Possible values are:
	// 1. no groups: Means no groups are given access.
	// 2. `["*"]`: All groups are allowed.
	// 3. `["group1", "group2"]`: Only certain groups are allowed. In this example only
	// _group1_ and _group2_ are allowed.
	Groups map[string]Ownership_AccessType `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=apis.auth.v1.Ownership_AccessType"`
	// Collaborator access to resource gives access to other user.
	// Must be the username (unique id) set in the authorization token.
	// The owner or the administrator can set this value. Possible values are:
	// 1. no collaborators: Means no users are given access.
	// 2. `["*"]`: All users are allowed.
	// 3. `["username1", "username2"]`: Only certain usernames are allowed. In this example only
	// _username1_ and _username2_ are allowed.
	Collaborators map[string]Ownership_AccessType `protobuf:"bytes,2,rep,name=collaborators,proto3" json:"collaborators,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=apis.auth.v1.Ownership_AccessType"`
	// Public access to resource may be assigned for access by the public userd
	// (-- api-linter: core::0140::reserved-words=disabled
	//
	//	aip.dev/not-precedent: need to continue using the name 'public' for compatibility --)
	Public        *Ownership_PublicAccessControl `protobuf:"bytes,3,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ownership_AccessControl) Reset() {
	*x = Ownership_AccessControl{}
	mi := &file_apis_auth_apiv1_ownership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ownership_AccessControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ownership_AccessControl) ProtoMessage() {}

func (x *Ownership_AccessControl) ProtoReflect() protoreflect.Message {
	mi := &file_apis_auth_apiv1_ownership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ownership_AccessControl.ProtoReflect.Descriptor instead.
func (*Ownership_AccessControl) Descriptor() ([]byte, []int) {
	return file_apis_auth_apiv1_ownership_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Ownership_AccessControl) GetGroups() map[string]Ownership_AccessType {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Ownership_AccessControl) GetCollaborators() map[string]Ownership_AccessType {
	if x != nil {
		return x.Collaborators
	}
	return nil
}

func (x *Ownership_AccessControl) GetPublic() *Ownership_PublicAccessControl {
	if x != nil {
		return x.Public
	}
	return nil
}

var File_apis_auth_apiv1_ownership_proto protoreflect.FileDescriptor

const file_apis_auth_apiv1_ownership_proto_rawDesc = "" +
	"\n" +
	"\x1fapis/auth/apiv1/ownership.proto\x12\fapis.auth.v1\"\xa0\x05\n" +
	"\tOwnership\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x129\n" +
	"\x04acls\x18\x02 \x01(\v2%.apis.auth.v1.Ownership.AccessControlR\x04acls\x1aM\n" +
	"\x13PublicAccessControl\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".apis.auth.v1.Ownership.AccessTypeR\x04type\x1a\xc4\x03\n" +
	"\rAccessControl\x12I\n" +
	"\x06groups\x18\x01 \x03(\v21.apis.auth.v1.Ownership.AccessControl.GroupsEntryR\x06groups\x12^\n" +
	"\rcollaborators\x18\x02 \x03(\v28.apis.auth.v1.Ownership.AccessControl.CollaboratorsEntryR\rcollaborators\x12C\n" +
	"\x06public\x18\x03 \x01(\v2+.apis.auth.v1.Ownership.PublicAccessControlR\x06public\x1a]\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\x0e2\".apis.auth.v1.Ownership.AccessTypeR\x05value:\x028\x01\x1ad\n" +
	"\x12CollaboratorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\x0e2\".apis.auth.v1.Ownership.AccessTypeR\x05value:\x028\x01\",\n" +
	"\n" +
	"AccessType\x12\b\n" +
	"\x04READ\x10\x00\x12\t\n" +
	"\x05WRITE\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02Bf\n" +
	"\x10com.apis.auth.v1B\x0eOwnershipProtoP\x01Z@github.com/grpc-framework/grpc-framework/v2/apis/auth/apiv1;authb\x06proto3"

var (
	file_apis_auth_apiv1_ownership_proto_rawDescOnce sync.Once
	file_apis_auth_apiv1_ownership_proto_rawDescData []byte
)

func file_apis_auth_apiv1_ownership_proto_rawDescGZIP() []byte {
	file_apis_auth_apiv1_ownership_proto_rawDescOnce.Do(func() {
		file_apis_auth_apiv1_ownership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apis_auth_apiv1_ownership_proto_rawDesc), len(file_apis_auth_apiv1_ownership_proto_rawDesc)))
	})
	return file_apis_auth_apiv1_ownership_proto_rawDescData
}

var file_apis_auth_apiv1_ownership_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apis_auth_apiv1_ownership_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_apis_auth_apiv1_ownership_proto_goTypes = []any{
	(Ownership_AccessType)(0),             // 0: apis.auth.v1.Ownership.AccessType
	(*Ownership)(nil),                     // 1: apis.auth.v1.Ownership
	(*Ownership_PublicAccessControl)(nil), // 2: apis.auth.v1.Ownership.PublicAccessControl
	(*Ownership_AccessControl)(nil),       // 3: apis.auth.v1.Ownership.AccessControl
	nil,                                   // 4: apis.auth.v1.Ownership.AccessControl.GroupsEntry
	nil,                                   // 5: apis.auth.v1.Ownership.AccessControl.CollaboratorsEntry
}
var file_apis_auth_apiv1_ownership_proto_depIdxs = []int32{
	3, // 0: apis.auth.v1.Ownership.acls:type_name -> apis.auth.v1.Ownership.AccessControl
	0, // 1: apis.auth.v1.Ownership.PublicAccessControl.type:type_name -> apis.auth.v1.Ownership.AccessType
	4, // 2: apis.auth.v1.Ownership.AccessControl.groups:type_name -> apis.auth.v1.Ownership.AccessControl.GroupsEntry
	5, // 3: apis.auth.v1.Ownership.AccessControl.collaborators:type_name -> apis.auth.v1.Ownership.AccessControl.CollaboratorsEntry
	2, // 4: apis.auth.v1.Ownership.AccessControl.public:type_name -> apis.auth.v1.Ownership.PublicAccessControl
	0, // 5: apis.auth.v1.Ownership.AccessControl.GroupsEntry.value:type_name -> apis.auth.v1.Ownership.AccessType
	0, // 6: apis.auth.v1.Ownership.AccessControl.CollaboratorsEntry.value:type_name -> apis.auth.v1.Ownership.AccessType
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_apis_auth_apiv1_ownership_proto_init() }
func file_apis_auth_apiv1_ownership_proto_init() {
	if File_apis_auth_apiv1_ownership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apis_auth_apiv1_ownership_proto_rawDesc), len(file_apis_auth_apiv1_ownership_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apis_auth_apiv1_ownership_proto_goTypes,
		DependencyIndexes: file_apis_auth_apiv1_ownership_proto_depIdxs,
		EnumInfos:         file_apis_auth_apiv1_ownership_proto_enumTypes,
		MessageInfos:      file_apis_auth_apiv1_ownership_proto_msgTypes,
	}.Build()
	File_apis_auth_apiv1_ownership_proto = out.File
	file_apis_auth_apiv1_ownership_proto_goTypes = nil
	file_apis_auth_apiv1_ownership_proto_depIdxs = nil
}
