/// Please use the following editor setup for this file:
// Tab size=2; Tabs as spaces; Clean up trailing whitepsace
//
// In vim add: au FileType proto setl sw=2 ts=2 expandtab list
//
// In vscode install vscode-proto3 extension and add this to your settings.json:
//    "[proto3]": {
//        "editor.tabSize": 2,
//        "editor.insertSpaces": true,
//        "editor.rulers": [80],
//        "editor.detectIndentation": true,
//        "files.trimTrailingWhitespace": true
//    }
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: apis/auth/apiv1/role.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Rule is the message used to construct custom RBAC roles
//
// #### Format
// The following shows the supported format for Rule:
//
// * Services: Is the gRPC service name in `[tag]<service name>` in lowercase
// * Apis: Is the API name in the service in lowercase
//
// Values can also be set to `*`, or start or end with `*` to allow multiple matches in services or apis.
//
// Services and APIs can also be denied by prefixing the value with a `!`. Note that on rule conflicts,
// denial will always be chosen.
//
// #### Examples
//
// * Allow any call:
//
// ```yaml
// Rule:
//   - Services: ["*"]
//     Apis: ["*"]
//
// ```
//
// * Allow only cluster operations:
//
// ```yaml
// Rule:
//   - services: ["cluster"]
//     apis: ["*"]
//
// ```
//
// * Allow inspection of any object and listings of only volumes
//
// ```yaml
// Rule:
//   - Services: ["volumes"]
//     Apis: ["*enumerate*"]
//   - Services: ["*"]
//     Apis: ["inspect*"]
//
// ```
//
// * Allow all volume call except create
//
// ```yaml
// Rule:
//   - Services: ["volumes"]
//     Apis: ["*", "!create"]
//
// ```
type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The gRPC service name in `[tag]<service name>` in lowercase
	Services []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	// The API name in the service in lowercase
	Apis          []string `protobuf:"bytes,2,rep,name=apis,proto3" json:"apis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_apis_auth_apiv1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_apis_auth_apiv1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_apis_auth_apiv1_role_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Rule) GetApis() []string {
	if x != nil {
		return x.Apis
	}
	return nil
}

// Role contains the rules for authorization
type Role struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the role
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// List of rules for authorization
	Rules         []*Rule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_apis_auth_apiv1_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_apis_auth_apiv1_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_apis_auth_apiv1_role_proto_rawDescGZIP(), []int{1}
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_apis_auth_apiv1_role_proto protoreflect.FileDescriptor

const file_apis_auth_apiv1_role_proto_rawDesc = "" +
	"\n" +
	"\x1aapis/auth/apiv1/role.proto\x12\fapis.auth.v1\"6\n" +
	"\x04Rule\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\x12\x12\n" +
	"\x04apis\x18\x02 \x03(\tR\x04apis\"D\n" +
	"\x04Role\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x05rules\x18\x02 \x03(\v2\x12.apis.auth.v1.RuleR\x05rulesBa\n" +
	"\x10com.apis.auth.v1B\tRoleProtoP\x01Z@github.com/grpc-framework/grpc-framework/v2/apis/auth/apiv1;authb\x06proto3"

var (
	file_apis_auth_apiv1_role_proto_rawDescOnce sync.Once
	file_apis_auth_apiv1_role_proto_rawDescData []byte
)

func file_apis_auth_apiv1_role_proto_rawDescGZIP() []byte {
	file_apis_auth_apiv1_role_proto_rawDescOnce.Do(func() {
		file_apis_auth_apiv1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apis_auth_apiv1_role_proto_rawDesc), len(file_apis_auth_apiv1_role_proto_rawDesc)))
	})
	return file_apis_auth_apiv1_role_proto_rawDescData
}

var file_apis_auth_apiv1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apis_auth_apiv1_role_proto_goTypes = []any{
	(*Rule)(nil), // 0: apis.auth.v1.Rule
	(*Role)(nil), // 1: apis.auth.v1.Role
}
var file_apis_auth_apiv1_role_proto_depIdxs = []int32{
	0, // 0: apis.auth.v1.Role.rules:type_name -> apis.auth.v1.Rule
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apis_auth_apiv1_role_proto_init() }
func file_apis_auth_apiv1_role_proto_init() {
	if File_apis_auth_apiv1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apis_auth_apiv1_role_proto_rawDesc), len(file_apis_auth_apiv1_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apis_auth_apiv1_role_proto_goTypes,
		DependencyIndexes: file_apis_auth_apiv1_role_proto_depIdxs,
		MessageInfos:      file_apis_auth_apiv1_role_proto_msgTypes,
	}.Build()
	File_apis_auth_apiv1_role_proto = out.File
	file_apis_auth_apiv1_role_proto_goTypes = nil
	file_apis_auth_apiv1_role_proto_depIdxs = nil
}
