#
# For more information see https://squidfunk.github.io/mkdocs-material/getting-started/
#

site_name: grpc-framework
nav:
    - Home: index.md
    - Getting Started:
        - Introduction: intro.md
    - Tutorials:
        - Introduction: tutorial/intro.md
        - Proto file: tutorial/proto.md
        - Setting up the server: tutorial/server.md
        - Connect with the client: tutorial/client.md
        - REST: tutorial/rest.md
        - Rate limit: tutorial/rate-limit.md 
        - Security:
            - TLS: tutorial/security/tls.md
            - Authentication: tutorial/security/authentication.md
            - RBAC authorization: tutorial/security/rbac.md
            - Resource authorization: tutorial/security/ownership.md
    - Reference:
        - Introduction: reference/intro.md
        - Style Guide: reference/style-guide.md
        - Generate Documentation: reference/gen-doc.md
        - REST: reference/rest.md
        - Rate Limiter: reference/rate-limiter.md
        - Security:
            - Introduction: reference/security/intro.md
            - Authentication: reference/security/authentication.md
            - Authorization: reference/security/authorization.md
            - TLS: reference/security/tls.md
            - Logging and Audit: reference/security/audit.md
    - About: about.md
markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: squidfunk
        repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
theme: 
    name: material
    features:
        - content.code.annotate
        # - content.tabs.link
        - content.tooltips
        # - header.autohide
        # - navigation.expand
        - navigation.indexes
        # - navigation.instant
        # - navigation.prune
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
                icon: material/brightness-7
                name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
                icon: material/brightness-4
                name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
site_dir: ../docs
